### ISSUE TITLE
What's the expected expiry when doing `$cacheItem->expiresAfter(0)`?

### ISSUE THREAD

**Issue by nicolas-grekas** [php-fig/cache#5]
I read the spec but the wording is misleading, or maybe I can't understand it completely:

```php
    /**
     * Sets the expiration time for this cache item.
     *
     * @param int|\DateInterval $time
     *   The period of time from the present after which the item MUST be considered
     *   expired. An integer parameter is understood to be the time in seconds until
     *   expiration. If null is passed explicitly, a default value MAY be used.
     *   If none is set, the value should be stored permanently or for as long as the
     *   implementation allows.
     *
     * @return static
     *   The called object.
     */
    public function expiresAfter($time);
```

What does `none` mean? zero? null? both?

**Comment by matthiasmullie** [comment]
I read it as: if `null` is passed explicitly and the implementing library doesn't allow for a different default expiration to be set, it should be stored permanently.

In other words, the default expiration time is infinity, unless the cache library allows you to set a different default.

**Comment by nicolas-grekas** [comment]
That's also how I understand the null value, but my question is about giving zero (`0`), this is where I'm confused.

**Comment by matthiasmullie** [comment]
I think the `none` applies not to the $time argument, but to the default cache expiration.

* If `null` is passed explicitly, the default cache expiration is used.
* If there is no default expiration (=`none`), the value will be stored permanently.

According to the rest of the phpdoc, a `0` $time would classify as this:

> An integer parameter is understood to be the time in seconds until expiration.

Which would mean that the item expires immediately (or well, at the end of the current second.)

**Comment by nicolas-grekas** [comment]
Oh, that's really likely! I'm closing then thanks.
